<?php
/**
 * db-config.php.example — PRODUCTION database configuration template.
 *
 * COPY this file to `db-config.php` in the project root and fill in your real
 * credentials. The app (api/config.php, install.php, scripts/dbcheck.php) loads
 * db-config.php automatically when present, WITHOUT touching your local XAMPP
 * defaults. It is also the recommended way to point the app at your hosting
 * provider's database (InfinityFree, Aiven, etc.) because shared hosts usually
 * do not let you set server environment variables.
 *
 *   cp db-config.example.php db-config.php      (bash)
 *   Copy-Item db-config.example.php db-config.php   (PowerShell)
 *
 * `db-config.php` is git-ignored (.gitignore) so your password is never
 * committed. Env vars (DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASS, DB_SSL,
 * DB_CA) still take precedence over this file where available (Docker/Render).
 *
 * Never consider committing a file containing real credentials.
 */

// Optional: OpenAI API key for the AI Financial Assistant (services/AIService.php
// + api/ai.php). When present, chat answers are generated by OpenAI; when absent
// the assistant runs in an offline, deterministic mode using your own records.
// Prefer the OPENAI_API_KEY environment variable on Docker/Render. The key is
// only ever read server-side and is never sent to the browser.
return [
    'host' => 'sql313.infinityfree.com',
    'port' => '3306',
    'name' => 'if0_42622623_moneywise1',
    'user' => 'if0_42622623',
    'pass' => 'PUT_YOUR_INFINITYFREE_MYSQL_PASSWORD_HERE',
    'ssl'  => '0',
    'ca'   => '', // path to a CA bundle if your host requires certificate verification
    'ai_api_key' => '', // optional: OpenAI key (see above)
];
